Repository twbs/examples, pull requests merged in 2023-03, with the labels that each got.

#48 Fix dependabot config
  .github/dependabot.yml
Labels: squash

#84 Update minor/patch dependencies and regenerate package-lock.json
  color-modes/package-lock.json
  icons-font/css/styles.css
  icons-font/css/styles.css.map
  icons-font/package-lock.json
  icons-font/package.json
  parcel/package-lock.json
  parcel/package.json
  sass-js-esm/package-lock.json
  sass-js-esm/package.json
  sass-js/css/styles.css
  sass-js/css/styles.css.map
  sass-js/package-lock.json
  sass-js/package.json
  starter/package-lock.json
  vite/package-lock.json
  vite/package.json
  vue/package-lock.json
  vue/package.json
  webpack/dist/main.js
  webpack/package-lock.json
  webpack/package.json
Labels: dependencies

#43 Fix popover in Vue example
  vue/src/js/main.js
Labels: bug

#113 Regenerate package-lock.json
  color-modes/package-lock.json
  icons-font/package-lock.json
  parcel/package-lock.json
  sass-js-esm/package-lock.json
  sass-js/package-lock.json
  vue/package-lock.json
  webpack/package-lock.json
Labels: dependencies

#124 Replace serve with sirv-cli
  color-modes/package-lock.json
  color-modes/package.json
  icons-font/package-lock.json
  icons-font/package.json
  sass-js-esm/package-lock.json
  sass-js-esm/package.json
  sass-js/package-lock.json
  sass-js/package.json
  starter/package-lock.json
  starter/package.json
Labels: dependencies

#139 Update minor and patch dependencies
  color-modes/package-lock.json
  color-modes/package.json
  icons-font/package-lock.json
  icons-font/package.json
  parcel/package-lock.json
  parcel/package.json
  sass-js-esm/package-lock.json
  sass-js-esm/package.json
  sass-js/package-lock.json
  sass-js/package.json
  vite/package-lock.json
  vite/package.json
  vue/package-lock.json
  vue/package.json
  webpack/package-lock.json
  webpack/package.json
Labels: dependencies
