Repository twbs/examples, pull requests merged in 2023-02, with the labels that each got.

#36 Fix URL of bootstrap-logo-black.svg
  icons-font/index.html
  parcel/src/index.html
  sass-js-esm/index.html
  sass-js/index.html
  vite/src/index.html
  vue/src/components/Header.vue
Labels: bug

#35 Bump vite dependency to 4.1.1
  vite/package-lock.json
  vite/package.json
  vue/package-lock.json
  vue/package.json
Labels: dependencies

#39 Update README.md to link to Bootstrap v5.3
  README.md
Labels: documentation

#37 Bump bootstrap dependencies to use latest popperjs version everywhere
  icons-font/package-lock.json
  icons-font/package.json
  parcel/package-lock.json
  parcel/package.json
  sass-js-esm/index.html
  sass-js-esm/package-lock.json
  sass-js/package-lock.json
  sass-js/package.json
  vite/package-lock.json
  vite/package.json
  webpack/package-lock.json
  webpack/package.json
Labels: dependencies
