Repository twbs/examples, pull requests merged in 2024-02, with the labels that each got.

#330 Fix edge case in `color-modes.js`
  color-modes/js/color-modes.js
Labels: bug

#399 Update all deps except for parcel
  color-modes/package-lock.json
  icons-font/package-lock.json
  react-nextjs/package-lock.json
  sass-js-esm/package-lock.json
  sass-js/package-lock.json
  starter/package-lock.json
  vite/package-lock.json
  vite/package.json
  vue/package-lock.json
  webpack/package-lock.json
  webpack/package.json
Labels: dependencies

#365 Finalize the color modes example
  README.md
  color-modes/index.html
Labels: enhancement
